---
name: Version Bump
run-name: Version Bump - v${{ inputs.version_number }}

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Project"
        required: true
        type: choice
        options:
          - bitwarden
          - bitwarden-api-api
          - bitwarden-api-identity
          - bitwarden-crypto
          - bitwarden-generators
          - bitwarden-json
          - cli
          - napi
      version_number:
        description: "New version (example: '2024.1.0')"
        required: true
      cut_rc_branch:
        description: "Cut RC branch?"
        default: true
        type: boolean

jobs:
  bump_version:
    name: "Bump ${{ inputs.project }} Version to v${{ inputs.version_number }}"
    runs-on: ubuntu-22.04
    steps:
      - name: Install rust
        uses: dtolnay/rust-toolchain@be73d7920c329f220ce78e0234b8f96b7ae60248 # stable
        with:
          toolchain: stable

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3

      - name: Install cargo-release
        run: cargo install cargo-edit

      - name: Login to Azure - CI Subscription
        uses: Azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
        with:
          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: "bitwarden-ci"
          secrets: "github-gpg-private-key,
            github-gpg-private-key-passphrase,
            github-pat-bitwarden-devops-bot-repo-scope"

      - name: Checkout Branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: main
          repository: bitwarden/sdk

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # v6.1.0
        with:
          gpg_private_key: ${{ steps.retrieve-secrets.outputs.github-gpg-private-key }}
          passphrase: ${{ steps.retrieve-secrets.outputs.github-gpg-private-key-passphrase }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create Version Branch
        id: branch
        env:
          VERSION: ${{ inputs.version_number }}
          PROJECT: ${{ inputs.project }}
        run: git switch -c sdk-${PROJECT}_version_bump_${VERSION}

      - name: Create Version Branch
        id: create-branch
        run: |
          NAME=version_bump_${{ github.ref_name }}_${{ inputs.project }}_${{ inputs.version_number }}
          git switch -c $NAME
          echo "name=$NAME" >> $GITHUB_OUTPUT

      ########################
      # VERSION BUMP SECTION #
      ########################

      ### napi
      - name: Bump @bitwarden/sdk-napi Version
        if: ${{ inputs.project == 'napi' }}
        working-directory: "crates/bitwarden-napi"
        run: |
          npm ci
          npm version ${{ inputs.version_number }}

      - name: Bump napi crate Version
        if: ${{ inputs.project == 'napi' }}
        run: cargo-set-version set-version -p bitwarden-napi ${{ inputs.version_number }}

      ### bitwarden

      - name: Bump bitwarden crate Version
        if: ${{ inputs.project == 'bitwarden' }}
        run: cargo-set-version set-version -p bitwarden ${{ inputs.version_number }}

      ### bitwarden-api-api

      - name: Bump bitwarden-api-api crate Version
        if: ${{ inputs.project == 'bitwarden-api-api' }}
        run: cargo-set-version set-version -p bitwarden-api-api ${{ inputs.version_number }}

      ### bitwarden-api-identity

      - name: Bump bitwarden-api-identity crate Version
        if: ${{ inputs.project == 'bitwarden-api-identity' }}
        run: cargo-set-version set-version -p bitwarden-api-identity ${{ inputs.version_number }}

      ### bitwarden-crypto

      - name: Bump bitwarden-crypto crate Version
        if: ${{ inputs.project == 'bitwarden-crypto' }}
        run: cargo-set-version set-version -p bitwarden-crypto ${{ inputs.version_number }}

      ### bitwarden-generators

      - name: Bump bitwarden-generators crate Version
        if: ${{ inputs.project == 'bitwarden-generators' }}
        run: cargo-set-version set-version -p bitwarden-generators ${{ inputs.version_number }}

      ### cli

      - name: Bump cli Version
        if: ${{ inputs.project == 'cli' }}
        run: cargo-set-version set-version -p bws ${{ inputs.version_number }}

      ### bitwarden-json

      - name: Bump bitwarden-json crate Version
        if: ${{ inputs.project == 'bitwarden-json' }}
        run: cargo-set-version set-version -p bitwarden-json ${{ inputs.version_number }}

      ############################
      # VERSION BUMP SECTION END #
      ############################

      - name: Setup git
        run: |
          git config --local user.email "106330231+bitwarden-devops-bot@users.noreply.github.com"
          git config --local user.name "bitwarden-devops-bot"

      - name: Check if version changed
        id: version-changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes_to_commit=TRUE" >> $GITHUB_OUTPUT
          else
            echo "changes_to_commit=FALSE" >> $GITHUB_OUTPUT
            echo "No changes to commit!";
          fi

      - name: Run prettier
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        run: |
          npm ci
          npm run prettier

      - name: Commit files
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        run: git commit -m "Bumped sdk-${{ inputs.project }} version to ${{ inputs.version_number }}" -a

      - name: Push changes
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        env:
          PR_BRANCH: ${{ steps.create-branch.outputs.name }}
        run: git push -u origin $PR_BRANCH

      - name: Create Version PR
        if: ${{ steps.version-changed.outputs.changes_to_commit == 'TRUE' }}
        id: create-pr
        env:
          GH_TOKEN: ${{ steps.retrieve-secrets.outputs.github-pat-bitwarden-devops-bot-repo-scope }}
          PR_BRANCH: ${{ steps.create-branch.outputs.name }}
          TITLE: "Bump version to ${{ inputs.version_number }}"
        run: |
          PR_URL=$(gh pr create --title "$TITLE" \
            --base "main" \
            --head "$PR_BRANCH" \
            --label "version update" \
            --label "automated pr" \
            --body "
              ## Type of change
              - [ ] Bug fix
              - [ ] New feature development
              - [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
              - [ ] Build/deploy pipeline (DevOps)
              - [X] Other

              ## Objective
              Automated ${{ inputs.project }} version bump to ${{ inputs.version_number }}")
          echo "pr_number=${PR_URL##*/}" >> $GITHUB_OUTPUT

      - name: Approve PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.create-pr.outputs.pr_number }}
        run: gh pr review $PR_NUMBER --approve

      - name: Merge PR
        env:
          GH_TOKEN: ${{ steps.retrieve-secrets.outputs.github-pat-bitwarden-devops-bot-repo-scope }}
          PR_NUMBER: ${{ steps.create-pr.outputs.pr_number }}
        run: gh pr merge $PR_NUMBER --squash --auto --delete-branch

  cut_rc:
    name: Cut RC branch
    needs: bump_version
    if: ${{ inputs.cut_rc_branch == true }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: main

      - name: Check if RC branch exists
        run: |
          remote_rc_branch_check=$(git ls-remote --heads origin rc | wc -l)
          if [[ "${remote_rc_branch_check}" -gt 0 ]]; then
            echo "Remote RC branch exists."
            echo "Please delete current RC branch before running again."
            exit 1
          fi

      - name: Cut RC branch
        run: |
          git switch --quiet --create rc
          git push --quiet --set-upstream origin rc
